server:
  port: 8083

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 141203
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntluanb22352003@gmail.com
    password: xcfjgiucrogcjogw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  signing.key: yGIVSMe9sP0iJDJMpSIph503ZM1uhQlfiPVjp/Hi1Yyv6Nd0kbwQ6omdwcAgA7xt
  valid-duration: 3600
  refresh-duration: 2592000
  reset-duration: 30
security:
  public-endpoints-post: /auth/**,/account/**,/password/**,/swagger-ui/**,/v3/api-docs/**,/v3/api-docs,/swagger-resources/**,/webjars/**,/v3/api-docs.yaml,/assets/**,/favicon.ico,/books/search
  public-endpoints-get: /auth/verify-email,/swagger-ui/**,/v3/api-docs/**,/v3/api-docs,/swagger-resources/**,/webjars/**,/v3/api-docs.yaml,/assets/**,/favicon.ico,/books/all,/books/detail,/chat/**
  permissions:
    admin_role: /admin/**
    user_role: /user/**
app:
  support-email: libmanage.support@gmail.com
  maintenance-mode: false
  verify-email-url: http://localhost:5173/verify-otp/
  reset-password-url: http://localhost:5173/reset-password/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: auth-service:8083