server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /user/users/**
          filters:
            - PreserveHostHeader
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /password/**, /account/**, /admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: gateway-service:8080

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

