server:
  port: 8084

spring:
  application:
    name: activity-log-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/lib_manager
      database: lib_manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/